### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by vbanthia-zz** [viche12345/fb-messenger-bball-cheater#1]
I tried installing this app and can see activity asking for override score. After adding score I played the game but not getting score which I saved in cheater app.

Could you let me know if this app actually works or not?

**Comment by viche12345** [comment]
Haha wow I didn't know someone would actually try this out! I'm pretty
flattered :)

Anyway, I haven't maintained this app for a long while now. The code worked
for a couple weeks at the time, but Facebook made a few updates to the
bball activity and broke the reflection based overrides I implemented.
However, you're more than welcome to fix it for the latest update!
